name = "tidal-collaborative-playlists"
main = "src/worker.ts"
compatibility_date = "2025-03-26"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "tidal-collab-db"
database_id = "faa2ee95-7a84-419f-8fdb-b7840e21d093"

[vars]
TIDAL_AUTH_BASE = "https://login.tidal.com"
TIDAL_API_BASE = "https://openapi.tidal.com/v2"
APP_URL = "https://tidal-collaborative-playlists.jeromeswannack.workers.dev"
